### ISSUE TITLE
Peer to Peer Code Review

### ISSUE THREAD

**Issue by kwambiee** [GedeonTS/To_Do_List#7]
:clap: You have done really good work on the implementation of the required functionalities. However, You could consider the following suggestions to improve your project;
- For best CSS practice, please ensure the body selector in your stylesheet appears at the top. 
- Kindly consider using the DRY technique for best code practices `const ArrayStoredParse = JSON.parse(localStorage.getItem('TaskToday'));`

**Comment by GedeonTS** [comment]
Thank you guys! :+1:
